name: My Project's CI/CD
on:
  push:
    branches: [ main ]
jobs:
  macOS_big_sur:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: first_step
        id: first_step
        uses: veertuinc/anka-vm-github-action@v1.3.2
        with:
          anka-vm-template-name: "big-sur-test"
          anka-vm-tag-name: "latest"
          anka-run-options: "--env"
          vm-commands: |
            echo \"First Step! Starting build process on `hostname`\"
            sw_vers
      - uses: actions/checkout@v2
      - name: second_step
        id: second_step
        uses: veertuinc/anka-vm-github-action@v1.3.2
        with:
          anka-vm-template-name: "big-sur-test"
          anka-vm-tag-name: "latest"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Second Step! Starting build process on `hostname`\"
            sw_vers
          
  macOS_mojave:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.2
        with:
          anka-vm-template-name: "mojave"
          anka-vm-tag-name: "latest"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Starting build process on `hostname`\"
            sw_vers
