name: My Project's CI/CD
on:
  push:
    branches: [ master ]
jobs:
  ios:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.2
        with:
          anka-vm-template-name: "11.4"
          anka-vm-tag-name: "vanilla+port-forward-22+brew-git"
          anka-run-options: "--env"
          vm-commands: |
            echo \"Starting build process on \$(hostname)\"
            ./build.sh && \
            ./cleanup.sh
          anka-cp-host-paths: |
            ./
            /Users/nathanpierce/cache
          artifact-files: |
            log.txt
            build/binaryfile-v1
