name: My Project's CI/CD
on:
  push:
    branches: [ main ]
jobs:
  macOS:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: veertuinc/anka-vm-github-action@v1.3.2
        with:
          anka-vm-template-name: "big-sur-test"
          anka-vm-tag-name: "latest"
          anka-run-options: "sudo "
          vm-commands: |
            echo \"Starting build process on \$(hostname)\"
            uname -a && \
            ls -la ls -la /Users/anka/Downloads
          artifact-files: |
            log.txt
            build/binaryfile-v1
